routes/web.php
<?php

use App\Http\Controllers\InvoiceController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [InvoiceController::class, 'index']);

Route::resource('invoice', InvoiceController::class);

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    use HasFactory;
}

app/Models/Invoice_item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice_item extends Model
{
    use HasFactory;
}

app/Models/Invoice_item_master.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice_item_master extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Invoice;
use App\Models\Invoice_item;
use App\Models\Invoice_item_master;
use Illuminate\Http\Request;

class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Invoice::where('isDeleted', 0)->get();

        return view('invoice.invoice')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Invoice_item_master::all();
        $data = ['itemMaster' => $data, 'url' => '/invoice'];

        return view("invoice.addInvoice")->with('data', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'invoiceItems' => 'required',
        ]);

        $invoiceItems = explode(",", $request->invoiceItems);
        $name = $request->name;
        $invDb = new Invoice();
        $invDb->name = $name;
        $invDb->save();
        $invDb->id;

        foreach ($invoiceItems as $it) {
            $itemDb = new Invoice_item();
            $itemDb->invoiceId =  $invDb->id;
            $itemDb->itemId  = $it;
            $itemDb->save();
        }

        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $invoiceData = Invoice::find($id);
        $itemMaster = Invoice_item_master::all();
        $selecredItemData = Invoice_item::leftJoin('invoice_item_masters', function ($join) {
            $join->on('invoice_items.itemId', '=', 'invoice_item_masters.id');
        })
            ->where('invoice_items.invoiceId', $id)
            ->where('invoice_items.isDeleted', 0)
            ->where('invoice_item_masters.isDeleted', 0)
            ->get([
                'invoice_items.id',
                'invoice_items.invoiceId',
                'invoice_items.itemId',
                'invoice_item_masters.itemName',
            ]);


        $temp = [];
        foreach ($selecredItemData as $dt) {
            array_push($temp, $dt['itemId']);
        }
        $oldItems = implode(",", $temp);


        $data = [
            'invoiceData' => $invoiceData, 'selecredItemData' => $selecredItemData, 'itemMaster' => $itemMaster,
            'oldItems' => $oldItems, 'type' => 'Update Invoice', 'url' => "/invoice/$id", 'method' => 'POST'
        ];



        return view("invoice.addInvoice")->with('data', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'name' => 'required',
            'invoiceItems' => 'required',
        ]);

        Invoice::where('id', $id)->update(['isDeleted' => 1]);
        Invoice_item::where('invoiceId', $id)->update(['isDeleted' => 1]);

        $invoiceItems = explode(",", $request->invoiceItems);
        $name = $request->name;
        $invDb = new Invoice();
        $invDb->name = $name;
        $invDb->save();
        $invDb->id;

        foreach ($invoiceItems as $it) {
            $itemDb = new Invoice_item();
            $itemDb->invoiceId =  $invDb->id;
            $itemDb->itemId  = $it;
            $itemDb->save();
        }

        return redirect('/');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Invoice::where('id', $id)->update(['isDeleted' => 1]);
        Invoice_item::where('invoiceId', $id)->update(['isDeleted' => 1]);
        return redirect('/');
    }
}

resources/views/invoice/addInvoice.blade.php
@extends('layouts.app')
@section('content')

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" />
<div class="container ">
    <br>
    <div class="card">
        <div class="card-header ">

            <h4 align="center"><b>Add Invoices</b></h4>

        </div>
        <div class="card-body">
            <form action="{{$data['url']}}" method="<?= $data['method'] ?? "POST" ?>">
                @csrf
                @if(isset($data['method']))
                @method('PUT')
                @endif



                <div class="form-group row mt-2">
                    <div class="col-md-2">
                        <label for="exampleFormControlInput1">Name :</label>
                    </div>
                    <div class="col-md-4">
                        <input type="name" name="name" class="form-control" placeholder="Name" value="<?= $data['invoiceData']['name'] ?? '' ?>">
                    </div>
                </div>

                <div class="form-group row mt-2">
                    <div class="col-md-2">
                        <label for="exampleFormControlInput1">Items :</label>
                    </div>
                    <div class="col-md-4">

                        @foreach($data['itemMaster'] as $dt)
                        <button type="button" class="btn btn-primary" onclick="addItem('{{$dt->id}}','{{$dt->itemName}}')">{{$dt->itemName}} <i class="fa fa-plus" aria-hidden="true"></i>
                        </button>
                        @endforeach
                    </div>
                </div>

                <div class="form-group row mt-2">
                    <div class="col-md-2">
                        <label for="exampleFormControlInput1">Added Items :</label>
                    </div>
                    <div class="col-md-4">
                        <span id="itemAdded">
                            @if(isset($data['selecredItemData']))
                            @foreach($data['selecredItemData'] as $selectedDt)


                            <button id="item_{{$selectedDt['itemId']}}" type="button" class="btn btn-success mb-2 ml-2" onclick="removeItem({{$selectedDt['itemId']}})">{{$selectedDt['itemName']}}<i class="fa fa-times" aria-hidden="true"></i>

                                @endforeach
                                @endif
                        </span>
                    </div>
                </div>
                <input type="hidden" name="invoiceItems" value="<?= $data['oldItems'] ?? '' ?>">

                <div class="form-group row mt-5">
                    <div class="col-md-2">

                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-success">
                            <?= $data['type'] ?? "Save Invoice"; ?>
                        </button>
                    </div>
                </div>


            </form>

        </div>
    </div>
</div>
<script>
    var itemIds = [];

    $(document).ready(function() {
        var string = $('input[name=invoiceItems]').val()
        console.log("string=", string)
        if (string)
            itemIds = string.split(',');

    });


    function addItem(itemId, itemName) {
        console.log("itemId=", itemId)
        if (itemIds.includes(itemId)) {
            toastr.error('Item already added');
        } else {
            itemIds.push(itemId)
            html = ' <button id="item_' + itemId + '" type="button" class="btn btn-success mb-2" onclick="removeItem(' + itemId + ')" >' + itemName + ' <i class="fa fa-times" aria-hidden="true"></i>';

            $("#itemAdded").append(html)

            $("input[name=invoiceItems]").val(itemIds);
            console.log("itemIds=", itemIds)
        }



    }

    function removeItem(id) {
        console.log("removeItem=", id);
        $("#item_" + id).remove();
        var removeItem = id;
        itemIds = jQuery.grep(itemIds, function(value) {
            return value != removeItem;
        });
        $("input[name=invoiceItems]").val(itemIds);
        console.log("itemIds=", itemIds)
    }
</script>

@endsection

resources/views/invoice/invoice.blade.php
@extends('layouts.app')
@section('content')


<div class="container ">
    <br>
    <div class="card">
        <div class="card-header ">

            <h4 align="center"><b>Invoices</b></h4>

        </div>
        <div class="card-body">
            <div align="right">
                <a href="invoice/create" class="btn btn-primary">Add Invoice</a>
            </div>
            <table class="table table-bordered mt-2">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Sr. No.</th>
                        <th scope="col">Name</th>
                        <th scope="col">Date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if(isset($data))
                    @foreach($data as $dt)
                    <tr>
                        <th scope="row">{{$dt->id}}</th>
                        <td>{{$dt->name}}</td>
                        <td>{{$dt->created_at}}</td>
                        <td>
                            <div class="row">
                                <div class="col-md-2">
                                    <a href="/invoice/{{$dt->id}}/edit" class="btn btn-primary ">Edit</a>
                                </div>
                                <div class="col-md-2">
                                    <form id="/invoice/{{$dt->id}}" + action="{{route('invoice.destroy', $dt->id)}}" method="post">
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    @endif
                </tbody>
            </table>

        </div>
    </div>
</div>


@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
</head>

<body>
    @yield('content')
</body>

</html>